const traits = {
  background: [
    { Blue: 14.29 },
    { Cyan: 14.29 },
    { Green: 14.29 },
    { Orange: 14.29 },
    { Purple: 14.29 },
    { Red: 14.29 },
    { Yellow: 14.29 },
  ],
  body: [
    { Alien: 5.0 },
    { Brown: 25.0 },
    { "Easter Pink": 10.0 },
    { Easter: 10.0 },
    { Grey: 25.0 },
    { White: 25.0 },
  ],
  clothes: [
    { "Artisan Shirt": 1.0 },
    { "Chef's Uniform": 1.0 },
    { "Hero Costume": 1.0 },
    { "Santa Costume": 1.0 },
    { "School Uniform": 1.0 },
    { "Thief's Costume": 1.0 },
    { Toga: 1.0 },
    { Vest: 1.0 },
    { "Work Overall": 1.0 },
    { "Ultra Bunny": 1.0 },
    { "Blue Stripped Shirt": 1.0 },
    { "Blue Work Shirt": 1.0 },
    { "Blue Shirt": 3.0 },
    { "Cyan Shirt": 3.0 },
    { "Green Shirt": 3.0 },
    { "Orange Shirt": 3.0 },
    { "Purple Shirt": 3.0 },
    { "Red Shirt": 3.0 },
    { "Yellow Shirt": 3.0 },
    { "Blue Golf Shirt": 3.0 },
    { "Cyan Golf Shirt": 3.0 },
    { "Green Golf Shirt": 3.0 },
    { "Orange Golf Shirt": 3.0 },
    { "Pink Golf Shirt": 2.0 },
    { "Red Golf Shirt": 3.0 },
    { "Yellow Golf Shirt": 3.0 },
    { "Burgundy Golf Shirt": 2.0 },
    { "Black Shirt": 2.0 },
    { "Blue Coat": 2.0 },
    { "Cyan Coat": 2.0 },
    { "Green Coat": 2.0 },
    { "Orange Coat": 2.0 },
    { "Purple Coat": 2.0 },
    { "Red Coat": 2.0 },
    { "Yellow Coat": 2.0 },
    { "Blue Hoodie": 2.0 },
    { "Cyan Hoodie": 2.0 },
    { "Green Hoodie": 3.0 },
    { "Pink Hoodie": 3.0 },
    { "Red Hoodie": 3.0 },
    { "Black Coat": 1.0 },
    { "Cyan Suit": 2.0 },
    { "Navy Suit": 2.0 },
    { "Orange Suit": 2.0 },
    { "Purple Suit": 3.0 },
    { "Red Suit": 2.0 },
    { "Yellow Suit": 2.0 },
    { "Green Suit": 2.0 },
  ],
  eyes: [
    { "Black Eye Mask": 2.0 },
    { "Cyan Eye Mask": 2.0 },
    { "Green Eye Mask": 2.0 },
    { "Orange Eye Mask": 2.0 },
    { "Pink Eye Mask": 2.0 },
    { "Red Eye Mask": 2.0 },
    { "Yellow Eye Mask": 2.0 },
    { "Black Eye Patch": 8.0 },
    { "Black Glasses": 18.0 },
    { "Gold Glasses": 18.0 },
    { "Pink Glasses": 18.0 },
    { "Silver Glasses": 16.0 },
    { "Gold Rimmed Glasses": 8.0 },
  ],
  head: [
    { "Artisan Beret": 3.0 },
    { Bandana: 3.0 },
    { crown: 3.0 },
    { "Fishing Hat": 3.0 },
    { "Chef's Hat": 3.0 },
    { "Golden Halo": 1.0 },
    { "Hair Ribbon": 3.0 },
    { "Hero Mask": 1.0 },
    { "Santa Hat": 3.0 },
    { "Witch's Hat": 3.0 },
    { "Blonde Hair": 5.0 },
    { "Green Hair": 5.0 },
    { "Grey Hair": 5.0 },
    { Afro: 4.0 },
    { "Red Hair": 5.0 },
    { "Black Hair": 5.0 },
    { "Blue Cap": 7.0 },
    { "Cyan Cap": 6.0 },
    { "Green Cap": 6.0 },
    { "Orange Cap": 6.0 },
    { "Purple Cap": 7.0 },
    { "Red Cap": 7.0 },
    { "Yellow Cap": 6.0 },
  ],
  mouth: [
    { Carrots: 25.0 },
    { Celery: 25.0 },
    { Mustache: 25.0 },
    { Spoon: 25.0 },
  ],
  neck: [
    { "Blue Scarf": 14.0 },
    { "Cyan Scarf": 13.0 },
    { "Green Scarf": 13.0 },
    { "Orange Scarf": 13.0 },
    { "Pink Scarf": 14.0 },
    { "Yellow Scarf": 13.0 },
    { "Red Scarf": 14.0 },
    { "Bow Tie": 6.0 },
  ],
  personality: [
    { Optimistic: 33.33 },
    { "Perfectly Balanced": 33.33 },
    { Pessemistic: 33.33 },
  ],
  wings: [{ "Angel Wings": 100.0 }],
};

export default traits;
